export const CHANGEPASSWORD__CHANGEPASSWORD = 'CHANGEPASSWORD__CHANGEPASSWORD';
export const CHANGEPASSWORD__INIT_FORM = 'CHANGEPASSWORD__INIT_FORM';
export const CHANGEPASSWORD__CLEAR_FORM_MESSAGES = 'CHANGEPASSWORD__CLEAR_FORM_MESSAGES';
export const CHANGEPASSWORD__SET_FORM_ERROR = 'CHANGEPASSWORD__SET_FORM_ERROR';
export const CHANGEPASSWORD__SET_FORM_SUCCESS = 'CHANGEPASSWORD__SET_FORM_SUCCESS';