export const LOGIN__LOGIN = 'LOGIN__LOGIN';
export const LOGIN__INIT_FORM = 'LOGIN__INIT_FORM';
export const LOGIN__CLEAR_FORM_MESSAGES = 'LOGIN__CLEAR_FORM_MESSAGES';
export const LOGIN__SET_FORM_ERROR = 'LOGIN__SET_FORM_ERROR';
export const LOGIN__SET_FORM_SUCCESS = 'LOGIN__SET_FORM_SUCCESS';
export const LOGIN__EMAIL_CHANGED = 'LOGIN__EMAIL_CHANGED';
export const LOGIN__PASSWORD_CHANGED = 'LOGIN__PASSWORD_CHANGED';
export const LOGIN__REVEAL_CHAGNED = 'LOGIN__REVEAL_CHAGNED';