export const EMAILCONFIRMATION__EMAILCONFIRMATION = 'EMAILCONFIRMATION__EMAILCONFIRMATION';
export const EMAILCONFIRMATION__INIT_FORM = 'EMAILCONFIRMATION__INIT_FORM';
export const EMAILCONFIRMATION__SET_FORM_ERROR = 'EMAILCONFIRMATION__SET_FORM_ERROR';
