export const REGISTRATION__REGISTRATION = 'REGISTRATION__REGISTRATION';
export const REGISTRATION__INIT_FORM = 'REGISTRATION__INIT_FORM';
export const REGISTRATION__CLEAR_FORM_MESSAGES = 'REGISTRATION__CLEAR_FORM_MESSAGES';
export const REGISTRATION__SET_FORM_ERROR = 'REGISTRATION__SET_FORM_ERROR';
export const REGISTRATION__SET_FORM_SUCCESS = 'REGISTRATION__SET_FORM_SUCCESS';